server:
  port: 8001

spring:
  application:
    name: member-mysql-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/project_crowd_funding?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dell
    password: dell

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: mysql8001
    prefer-ip-address: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 10000

logging:
  level:
    crowdfunding.mapper: debug
    crowdfunding.test: debug