server:
  port: 80

spring:
  application:
    name: member-gateway-service
  session:
    store-type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: member-gateway-service

zuul:
  routes:
    member-portal:
      service-id: member-authentication-consumer
      path: /**
    member-project:
      service-id: member-project-consumer
      path: /project/**
    member-order:
      service-id: member-order-consumer
      path: /order/**
    member-payment:
      service-id: member-payment-consumer
      path: /payment/**
  ignored-services: "*"
  sensitive-headers: "*"
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
